# Generated by Django 4.1.3 on 2023-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_invoice',
            name='date',
            field=models.DateField(),
        ),
    ]
