# Generated by Django 4.1.3 on 2023-12-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_alter_model_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_invoice',
            name='customername',
            field=models.CharField(max_length=50, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='model_invoice',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='model_invoice_detail',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='model_invoice_detail',
            name='price',
            field=models.IntegerField(default=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='model_invoice_detail',
            name='quantity',
            field=models.IntegerField(default=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='model_invoice_detail',
            name='unitprice',
            field=models.IntegerField(default=True, null=True, verbose_name='Unit Price'),
        ),
    ]
